@startuml
'https://plantuml.com/class-diagram

Zimmer "*" --> "1" Kategorie
Zimmer "1" <-- "*" Buchung
Gast "1" <-- "*" Buchung
Mitarbeiter "1" <-- "*" Arbeitszuweisung
Paket "1" <-- "*" Arbeitszuweisung
Buchung "1" <-- "*" Leitungszuweisung
Paket "1" <-- "*" Leitungszuweisung
Mitarbeiter "*" <-- "1" Fachgebiet
Mitarbeiter "1" <-- "*" Reinigungszuweisung
Zimmer "1" <-- "1" Reinigungszuweisung

/'Paket -- Luxuspaket
Paket -- Basispaket
Luxuspaket -- Basispaket'/

class Zimmer{
-nummer:int
-personen:int
}

class Mitarbeiter{
- svnnr:int
- name:string
- adresse:string
}

class Gast{
- kundenNr: int
- name: string
- adresse:string
}

class Buchung{
- von:LocalDate
- bis: LocalDate
- anzahlParkete:int
}

class Paket {
-bezeichnung:string
-preis:double
}

class Arbeitszuweisung{}

class Leitungszuweisung{}


class Kategorie {
-id:int
-bezeichnung: string
}

@enduml